version: "2"
services:
  measurify:
    build: .
    image: measurify
    container_name: measurify
    ports:
      - "8084:8084"
      - "443:443"
    depends_on:
      - database
    volumes:
        - ./resources:/resources   
  database:
    image: mongo
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"
